#!/command/with-contenv sh

log() {
   echo "$1" | s6-log p"[generate-api-key-and-secret]" 1
}

f=/etc/webtor/secrets/api.env
mkdir -p "$(dirname "$f")"
if [ -n "$API_KEY" ] && [ -n "$API_SECRET" ]; then
  log "using provided API_KEY and API_SECRET"
  key=$API_KEY
  secret=$API_SECRET
elif [ -f $f ]; then
  log "key file ${f} already exists"
  exit
else
  log "generating API_KEY and API_SECRET"
  key=$(uuidgen | tr '[:upper:]' '[:lower:]')
  secret=$(uuidgen | sha1sum | head -c 40)
fi
log "storing API_KEY and API_SECRET to ${f}"
echo "API_KEY=${key}" > $f
echo "API_SECRET=${secret}" >> $f
